name: Notion Changes Detection (Test)

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Skip PR creation and only run detection'
        type: boolean
        default: true
      force_pr:
        description: 'Create PR even if no changes detected'
        type: boolean
        default: false

jobs:
  test-environment-changes:
    uses: ./.github/workflows/_shared-notion-workflow.yml
    with:
      environment: test
      dry_run: ${{ inputs.dry_run }}
      force_pr: ${{ inputs.force_pr }}
    secrets:
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY_TEST }}